[project]
name = "system-design"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "passlib[bcrypt]>=1.7.4",
    "psycopg[binary]>=3.3.5",
    "pwdlib[argon2]>=0.3.1",
    "pyjwt>=2.13.0",
    "sqlalchemy>=2.0.53",
    "uvicorn>=0.53.0",
    "websockets>=17.1",
]
